# -*- coding: utf-8 -*-
"""question_store

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJa2Zowyqao2xjsk9MgjMAti0qc3j9CU
"""

# backend/app/storage/question_store.py

import json
from pathlib import Path
from typing import Optional, Dict, Any
from app.core.paths import QUESTIONS_DIR

class QuestionStore:
    """
    data/questions/{pdf_id}.questions.json 파일에서 문제를 조회함
    """

    @staticmethod
    def get_question(pdf_id: str, question_id: str) -> Optional[Dict[str, Any]]:
        # [수정 1] 파일명 규칙 맞춤 (ex: Ch6.questions.json)
        file_path = QUESTIONS_DIR / f"{pdf_id}.questions.json"

        if not file_path.exists():
            print(f"File not found: {file_path}")
            return None

        try:
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)

            # [수정 2] 원지우님 데이터 구조 반영
            # 루트가 dict이고 "questions" 키 안에 리스트가 있는 구조 처리
            if isinstance(data, dict) and "questions" in data:
                questions_list = data["questions"]
            else:
                # 혹시라도 리스트로 바로 되어있는 경우를 대비
                questions_list = data if isinstance(data, list) else []

            # 리스트에서 ID로 문제 찾기
            for q in questions_list:
                # 원지우님 파일의 id 필드는 "question_id" 임
                if q.get("question_id") == question_id:
                    return q

            return None
        except Exception as e:
            print(f"Error loading question: {e}")
            return None