# -*- coding: utf-8 -*-
"""grading_service

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12vzyCS6i9hLACVBUeh0GpspHVDDumc5r
"""

# backend/app/services/grading_service.py

from datetime import datetime
from typing import Dict, Any
from app.storage.question_store import QuestionStore
from app.storage.history_store import HistoryStore

# [수정됨] 에러 원인 해결!
# WrongNoteResponse, WrongQuestionItem은 이제 필요 없어서 지웠습니다.
from app.models.grading import GradeResponse

class GradingService:

    @staticmethod
    def grade_answer(pdf_id: str, question_id: str, user_answer: str, user_id: str) -> GradeResponse:
        # 1. 문제 조회
        question_data = QuestionStore.get_question(pdf_id, question_id)
        if not question_data:
            raise ValueError(f"Question not found: {question_id} in {pdf_id}")

        # 필드명 매핑 (엔진 출력 형식에 맞춤)
        q_type = question_data.get("type", "MCQ")
        # 엔진은 correct_answer로 저장, 하위 호환성을 위해 answer도 확인
        correct_answer = str(question_data.get("correct_answer") or question_data.get("answer", "")).strip()
        q_text = question_data.get("question_text", question_data.get("question", ""))

        user_answer_str = user_answer.strip()

        # 2. 채점 로직
        is_correct = False
        feedback = ""

        if q_type == "MCQ":
            # [객관식] 대소문자 무시 (A == a)
            is_correct = (user_answer_str.upper() == correct_answer.upper())
        else:
            # [단답형/주관식] 대소문자 무시 (Apple == apple)
            is_correct = (user_answer_str.lower() == correct_answer.lower())

        score = 10 if is_correct else 0
        feedback = "정답입니다!" if is_correct else f"아쉽네요. 정답은 {correct_answer}입니다."

        # 3. 히스토리 저장
        standardized_question = {
            "id": question_data.get("question_id"),
            "question": q_text,
            "answer": correct_answer,
            "explanation": question_data.get("explanation", ""),
            "evidence": question_data.get("evidence", None)
        }

        graded_at = datetime.now().isoformat()
        HistoryStore.save_attempt(user_id, standardized_question, user_answer_str, is_correct)

        # 4. 응답 생성
        return GradeResponse(
            question_id=question_id,
            type=q_type,
            is_correct=is_correct,
            score=score,
            user_answer=user_answer_str,
            correct_answer=correct_answer,
            feedback=feedback,
            graded_at=graded_at
        )
