# -*- coding: utf-8 -*-
"""history_service

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihsxeG1aGdmlgNqF9_R29f-94dLNV2Sx
"""

# backend/app/services/history_service.py

from app.storage.history_store import HistoryStore
# [수정] 모델 임포트 경로 변경 (grading -> history)
from app.models.history import WrongNoteResponse, WrongQuestionItem

class HistoryService:

    @staticmethod
    def get_wrong_notes(user_id: str) -> WrongNoteResponse:
        """
        사용자의 오답 노트 데이터를 가져와서 응답 모델로 변환합니다.
        """
        wrong_items_data = HistoryStore.get_wrong_questions(user_id)

        items = [WrongQuestionItem(**item) for item in wrong_items_data]

        return WrongNoteResponse(
            user_id=user_id,
            items=items,
            total=len(items)
        )